on : push
jobs :
     first-job:
         runs-on : ubuntu-latest
         steps : 
                - run: node --version
                - run: npm --version
                - run: npm install
                - uses: actions/checkout@v3
                - run: npx eslint index.js
                - run: node index.js